vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        products:
            uri_prefix: /img/products
            upload_destination: '%kernel.project_dir%/public/img/products'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
